# Run operator locally
Here is an example for the R ``mean`` operator shown previously but this time it is executed locally from your favorite development environment. This example is a brief introduction on creating operators locally.

* Go to the ``crabs workflow``
* Right click on the "mean" data step and select **Reset**

The step should go red.

* Go to the ``mean`` data step (if its not open already then double click on the ``mean`` data step)
* Copy the url and identify the workflowId and stepId.

The url structure is https://tercen.com/core/index.html#ds/{workflowId}/{stepId}

where workflowId and stepId is a hexadecimal number(with hypens).

An example is the following:

* Install rtercen package

```
devtools::install_github("tercen/rtercen", ref = "2.10")
```

* Load the appriopiate libraries
```
library(rtercen)
library(plyr)
```

* Replace the long string of Xs (length 32) and the long string of Ys (length 36) indicated below with the actual workflowId and stepId values.

```
workflowId = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
stepId = "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
```
* Create a Tercen client object using your actual username and password

```
client = TercenClient$new(myusername, mypassword)
```

* Get the cube query defined by your workflow
```
query = client$getCubeQuery(workflowId, stepId)
# inspect query as json
# query$toJson()
```
* Execute the query and get the data
```
cube = query$execute()
```
* Get the data as a data frame
```
df <- cube$sourceTable$as.data.frame()
```
* Execute some computation
```
computed.df <- ddply(df, c(".ids"), summarize, mean = mean(.values))
```
In this instance it is a mean operator.

* Send the result to Tercen
```
query$setResult(computed.df)
```
* Go to the ``crabs workflow`` and refresh the page

The ``mean`` data step should now be green. Even though the execution has taken place locally on your computer.

* Open the ``mean results`` data step and check the results. It should be the same results view as when the operator was run on before on the Tercen server.


More documentation can be found at https://github.com/tercen/rtercen